name: Continuous Delivery of Land DA Container

on:
  push:
    branches: [ "feature/citest" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  deploy:
    name: Land DA CI/CD Workflow 
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive
        
    - uses: jitterbit/get-changed-files@v1
      id: abc
      with:
        format: space-delimited
        token: ${{ secrets.GITHUB_TOKEN }}        
          
    - name: Login to DockerHub Registry
      env:
          DOCKER_TOKEN: ${{ env.DOCKER_TOKEN }}
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

    - name: Build Docker Image
      run: |
        echo "maximize disk space on git-runner ..."
        df -h 
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo rm -rf "/usr/local/share/boost"
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"
        df -h
        echo "docker build ..."
        docker build -t ufs-noahmp_landa:develop .
        df -h
    - name: Docker Tag and Push ufs-noahmp_landa:develop to DockerHub
      run: | 
       docker images 
       if [[ $(docker image inspect ufs-noahmp_landa:develop) ]]; then
        echo "docker push tag ..."
        docker tag ufs-noahmp_landa:develop jongkim2004/ufs-noahmp_landa:develop
        docker push jongkim2004/ufs-noahmp_landa:develop
       else
        echo "ufs-noahmp_landa:develop was not generated ..."
       fi
       
    - name: Docker Logout
      run: |
       docker logout
