name: Continuous Delivery of Land DA Container

on:
  push:
    branches: [ "release/public-v1.0.0" ]
  pull_request:
    branches: [ "release/public-v1.0.0" ]

jobs:
  deploy:
    name: Land DA CI/CD Workflow 
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Build HTML
      uses: ammaraskar/sphinx-action@master
    
#    - name: Upload artifacts
#      uses: actions/upload-artifact@v3
#      with:
#        name: html-docs
#        path: docs/build/html/
    
#    - name: Deploy
#      uses: peaceiris/actions-gh-pages@v3
#      if: github.ref == './test/ci/Dockerfile'
#      with:
#        github_token: ${{ secrets.GITHUB_TOKEN }}
#        publish_dir: docs/build/html
        
    - uses: jitterbit/get-changed-files@v1
      id: abc
      with:
        format: space-delimited
        token: ${{ secrets.GITHUB_TOKEN }}        
          
#    - name: Login to DockerHub Registry
#      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

    - name: Build Docker Image
      run: |
        echo "maximize disk space on git-runner ..."
        df -h 
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo rm -rf "/usr/local/share/boost"
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"
        df -h
        echo "docker image build ..."
        docker build --file "./test/ci/Dockerfile" -t ufs-noahmp_landa:develop .
        
    - name: Check Docker Image
      run: | 
       docker images 
       if [[ $(docker image inspect ufs-noahmp_landa:develop) ]]; then
        echo "ufs-noahmp_landa:develop generated ..."
       else
        echo "ufs-noahmp_landa:develop was not generated ..."
        exit 1
       fi

#    - name: Docker Logout
#      run: |
#       docker logout
